/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as SolicitacaoMovimentacaoRouteImport } from './routes/solicitacao-movimentacao'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PesquisasRouteImport } from './routes/pesquisas'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitacaoMovimentacaoRoute = SolicitacaoMovimentacaoRouteImport.update({
  id: '/solicitacao-movimentacao',
  path: '/solicitacao-movimentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisasRoute = PesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/inicio': typeof InicioRoute
  '/pesquisas': typeof PesquisasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitacao-movimentacao': typeof SolicitacaoMovimentacaoRoute
  '/usuarios': typeof UsuariosRoute
  '/p/$token': typeof PTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/inicio': typeof InicioRoute
  '/pesquisas': typeof PesquisasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitacao-movimentacao': typeof SolicitacaoMovimentacaoRoute
  '/usuarios': typeof UsuariosRoute
  '/p/$token': typeof PTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/inicio': typeof InicioRoute
  '/pesquisas': typeof PesquisasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitacao-movimentacao': typeof SolicitacaoMovimentacaoRoute
  '/usuarios': typeof UsuariosRoute
  '/p/$token': typeof PTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/inicio'
    | '/pesquisas'
    | '/reset-password'
    | '/solicitacao-movimentacao'
    | '/usuarios'
    | '/p/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/inicio'
    | '/pesquisas'
    | '/reset-password'
    | '/solicitacao-movimentacao'
    | '/usuarios'
    | '/p/$token'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/inicio'
    | '/pesquisas'
    | '/reset-password'
    | '/solicitacao-movimentacao'
    | '/usuarios'
    | '/p/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  DashboardRoute: typeof DashboardRoute
  InicioRoute: typeof InicioRoute
  PesquisasRoute: typeof PesquisasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SolicitacaoMovimentacaoRoute: typeof SolicitacaoMovimentacaoRoute
  UsuariosRoute: typeof UsuariosRoute
  PTokenRoute: typeof PTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitacao-movimentacao': {
      id: '/solicitacao-movimentacao'
      path: '/solicitacao-movimentacao'
      fullPath: '/solicitacao-movimentacao'
      preLoaderRoute: typeof SolicitacaoMovimentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisas': {
      id: '/pesquisas'
      path: '/pesquisas'
      fullPath: '/pesquisas'
      preLoaderRoute: typeof PesquisasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  DashboardRoute: DashboardRoute,
  InicioRoute: InicioRoute,
  PesquisasRoute: PesquisasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SolicitacaoMovimentacaoRoute: SolicitacaoMovimentacaoRoute,
  UsuariosRoute: UsuariosRoute,
  PTokenRoute: PTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
