/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as SolicitacaoMovimentacaoRouteImport } from './routes/solicitacao-movimentacao'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PesquisasRouteImport } from './routes/pesquisas'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as MovimentacoesAdmissoesRouteImport } from './routes/movimentacoes-admissoes'
import { Route as MestreRouteImport } from './routes/mestre'
import { Route as MapaAlocacaoRouteImport } from './routes/mapa-alocacao'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as IdeiasRouteImport } from './routes/ideias'
import { Route as HistoricoAdmissoesRouteImport } from './routes/historico-admissoes'
import { Route as GeracoesRouteImport } from './routes/geracoes'
import { Route as FeedbacksRouteImport } from './routes/feedbacks'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as EmpresaMembrosRouteImport } from './routes/empresa-membros'
import { Route as EmpresaConfigRouteImport } from './routes/empresa-config'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChamadaRouteImport } from './routes/chamada'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AniversariantesRouteImport } from './routes/aniversariantes'
import { Route as AnaliseFaltasRouteImport } from './routes/analise-faltas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VagaTokenRouteImport } from './routes/vaga.$token'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as ESlugRouteImport } from './routes/e.$slug'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitacaoMovimentacaoRoute = SolicitacaoMovimentacaoRouteImport.update({
  id: '/solicitacao-movimentacao',
  path: '/solicitacao-movimentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisasRoute = PesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesAdmissoesRoute = MovimentacoesAdmissoesRouteImport.update({
  id: '/movimentacoes-admissoes',
  path: '/movimentacoes-admissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MestreRoute = MestreRouteImport.update({
  id: '/mestre',
  path: '/mestre',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaAlocacaoRoute = MapaAlocacaoRouteImport.update({
  id: '/mapa-alocacao',
  path: '/mapa-alocacao',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeiasRoute = IdeiasRouteImport.update({
  id: '/ideias',
  path: '/ideias',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoAdmissoesRoute = HistoricoAdmissoesRouteImport.update({
  id: '/historico-admissoes',
  path: '/historico-admissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GeracoesRoute = GeracoesRouteImport.update({
  id: '/geracoes',
  path: '/geracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbacksRoute = FeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaMembrosRoute = EmpresaMembrosRouteImport.update({
  id: '/empresa-membros',
  path: '/empresa-membros',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaConfigRoute = EmpresaConfigRouteImport.update({
  id: '/empresa-config',
  path: '/empresa-config',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadaRoute = ChamadaRouteImport.update({
  id: '/chamada',
  path: '/chamada',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AniversariantesRoute = AniversariantesRouteImport.update({
  id: '/aniversariantes',
  path: '/aniversariantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseFaltasRoute = AnaliseFaltasRouteImport.update({
  id: '/analise-faltas',
  path: '/analise-faltas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagaTokenRoute = VagaTokenRouteImport.update({
  id: '/vaga/$token',
  path: '/vaga/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise-faltas': typeof AnaliseFaltasRoute
  '/aniversariantes': typeof AniversariantesRoute
  '/auditoria': typeof AuditoriaRoute
  '/cadastro': typeof CadastroRoute
  '/chamada': typeof ChamadaRoute
  '/dashboard': typeof DashboardRoute
  '/empresa-config': typeof EmpresaConfigRoute
  '/empresa-membros': typeof EmpresaMembrosRoute
  '/experiencia': typeof ExperienciaRoute
  '/feedbacks': typeof FeedbacksRoute
  '/geracoes': typeof GeracoesRoute
  '/historico-admissoes': typeof HistoricoAdmissoesRoute
  '/ideias': typeof IdeiasRoute
  '/inicio': typeof InicioRoute
  '/mapa-alocacao': typeof MapaAlocacaoRoute
  '/mestre': typeof MestreRoute
  '/movimentacoes-admissoes': typeof MovimentacoesAdmissoesRoute
  '/notas': typeof NotasRoute
  '/pesquisas': typeof PesquisasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitacao-movimentacao': typeof SolicitacaoMovimentacaoRoute
  '/usuarios': typeof UsuariosRoute
  '/e/$slug': typeof ESlugRoute
  '/p/$token': typeof PTokenRoute
  '/vaga/$token': typeof VagaTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise-faltas': typeof AnaliseFaltasRoute
  '/aniversariantes': typeof AniversariantesRoute
  '/auditoria': typeof AuditoriaRoute
  '/cadastro': typeof CadastroRoute
  '/chamada': typeof ChamadaRoute
  '/dashboard': typeof DashboardRoute
  '/empresa-config': typeof EmpresaConfigRoute
  '/empresa-membros': typeof EmpresaMembrosRoute
  '/experiencia': typeof ExperienciaRoute
  '/feedbacks': typeof FeedbacksRoute
  '/geracoes': typeof GeracoesRoute
  '/historico-admissoes': typeof HistoricoAdmissoesRoute
  '/ideias': typeof IdeiasRoute
  '/inicio': typeof InicioRoute
  '/mapa-alocacao': typeof MapaAlocacaoRoute
  '/mestre': typeof MestreRoute
  '/movimentacoes-admissoes': typeof MovimentacoesAdmissoesRoute
  '/notas': typeof NotasRoute
  '/pesquisas': typeof PesquisasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitacao-movimentacao': typeof SolicitacaoMovimentacaoRoute
  '/usuarios': typeof UsuariosRoute
  '/e/$slug': typeof ESlugRoute
  '/p/$token': typeof PTokenRoute
  '/vaga/$token': typeof VagaTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise-faltas': typeof AnaliseFaltasRoute
  '/aniversariantes': typeof AniversariantesRoute
  '/auditoria': typeof AuditoriaRoute
  '/cadastro': typeof CadastroRoute
  '/chamada': typeof ChamadaRoute
  '/dashboard': typeof DashboardRoute
  '/empresa-config': typeof EmpresaConfigRoute
  '/empresa-membros': typeof EmpresaMembrosRoute
  '/experiencia': typeof ExperienciaRoute
  '/feedbacks': typeof FeedbacksRoute
  '/geracoes': typeof GeracoesRoute
  '/historico-admissoes': typeof HistoricoAdmissoesRoute
  '/ideias': typeof IdeiasRoute
  '/inicio': typeof InicioRoute
  '/mapa-alocacao': typeof MapaAlocacaoRoute
  '/mestre': typeof MestreRoute
  '/movimentacoes-admissoes': typeof MovimentacoesAdmissoesRoute
  '/notas': typeof NotasRoute
  '/pesquisas': typeof PesquisasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitacao-movimentacao': typeof SolicitacaoMovimentacaoRoute
  '/usuarios': typeof UsuariosRoute
  '/e/$slug': typeof ESlugRoute
  '/p/$token': typeof PTokenRoute
  '/vaga/$token': typeof VagaTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise-faltas'
    | '/aniversariantes'
    | '/auditoria'
    | '/cadastro'
    | '/chamada'
    | '/dashboard'
    | '/empresa-config'
    | '/empresa-membros'
    | '/experiencia'
    | '/feedbacks'
    | '/geracoes'
    | '/historico-admissoes'
    | '/ideias'
    | '/inicio'
    | '/mapa-alocacao'
    | '/mestre'
    | '/movimentacoes-admissoes'
    | '/notas'
    | '/pesquisas'
    | '/reset-password'
    | '/solicitacao-movimentacao'
    | '/usuarios'
    | '/e/$slug'
    | '/p/$token'
    | '/vaga/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise-faltas'
    | '/aniversariantes'
    | '/auditoria'
    | '/cadastro'
    | '/chamada'
    | '/dashboard'
    | '/empresa-config'
    | '/empresa-membros'
    | '/experiencia'
    | '/feedbacks'
    | '/geracoes'
    | '/historico-admissoes'
    | '/ideias'
    | '/inicio'
    | '/mapa-alocacao'
    | '/mestre'
    | '/movimentacoes-admissoes'
    | '/notas'
    | '/pesquisas'
    | '/reset-password'
    | '/solicitacao-movimentacao'
    | '/usuarios'
    | '/e/$slug'
    | '/p/$token'
    | '/vaga/$token'
  id:
    | '__root__'
    | '/'
    | '/analise-faltas'
    | '/aniversariantes'
    | '/auditoria'
    | '/cadastro'
    | '/chamada'
    | '/dashboard'
    | '/empresa-config'
    | '/empresa-membros'
    | '/experiencia'
    | '/feedbacks'
    | '/geracoes'
    | '/historico-admissoes'
    | '/ideias'
    | '/inicio'
    | '/mapa-alocacao'
    | '/mestre'
    | '/movimentacoes-admissoes'
    | '/notas'
    | '/pesquisas'
    | '/reset-password'
    | '/solicitacao-movimentacao'
    | '/usuarios'
    | '/e/$slug'
    | '/p/$token'
    | '/vaga/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseFaltasRoute: typeof AnaliseFaltasRoute
  AniversariantesRoute: typeof AniversariantesRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CadastroRoute: typeof CadastroRoute
  ChamadaRoute: typeof ChamadaRoute
  DashboardRoute: typeof DashboardRoute
  EmpresaConfigRoute: typeof EmpresaConfigRoute
  EmpresaMembrosRoute: typeof EmpresaMembrosRoute
  ExperienciaRoute: typeof ExperienciaRoute
  FeedbacksRoute: typeof FeedbacksRoute
  GeracoesRoute: typeof GeracoesRoute
  HistoricoAdmissoesRoute: typeof HistoricoAdmissoesRoute
  IdeiasRoute: typeof IdeiasRoute
  InicioRoute: typeof InicioRoute
  MapaAlocacaoRoute: typeof MapaAlocacaoRoute
  MestreRoute: typeof MestreRoute
  MovimentacoesAdmissoesRoute: typeof MovimentacoesAdmissoesRoute
  NotasRoute: typeof NotasRoute
  PesquisasRoute: typeof PesquisasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SolicitacaoMovimentacaoRoute: typeof SolicitacaoMovimentacaoRoute
  UsuariosRoute: typeof UsuariosRoute
  ESlugRoute: typeof ESlugRoute
  PTokenRoute: typeof PTokenRoute
  VagaTokenRoute: typeof VagaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitacao-movimentacao': {
      id: '/solicitacao-movimentacao'
      path: '/solicitacao-movimentacao'
      fullPath: '/solicitacao-movimentacao'
      preLoaderRoute: typeof SolicitacaoMovimentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisas': {
      id: '/pesquisas'
      path: '/pesquisas'
      fullPath: '/pesquisas'
      preLoaderRoute: typeof PesquisasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes-admissoes': {
      id: '/movimentacoes-admissoes'
      path: '/movimentacoes-admissoes'
      fullPath: '/movimentacoes-admissoes'
      preLoaderRoute: typeof MovimentacoesAdmissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mestre': {
      id: '/mestre'
      path: '/mestre'
      fullPath: '/mestre'
      preLoaderRoute: typeof MestreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-alocacao': {
      id: '/mapa-alocacao'
      path: '/mapa-alocacao'
      fullPath: '/mapa-alocacao'
      preLoaderRoute: typeof MapaAlocacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideias': {
      id: '/ideias'
      path: '/ideias'
      fullPath: '/ideias'
      preLoaderRoute: typeof IdeiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico-admissoes': {
      id: '/historico-admissoes'
      path: '/historico-admissoes'
      fullPath: '/historico-admissoes'
      preLoaderRoute: typeof HistoricoAdmissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geracoes': {
      id: '/geracoes'
      path: '/geracoes'
      fullPath: '/geracoes'
      preLoaderRoute: typeof GeracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedbacks': {
      id: '/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof FeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa-membros': {
      id: '/empresa-membros'
      path: '/empresa-membros'
      fullPath: '/empresa-membros'
      preLoaderRoute: typeof EmpresaMembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa-config': {
      id: '/empresa-config'
      path: '/empresa-config'
      fullPath: '/empresa-config'
      preLoaderRoute: typeof EmpresaConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamada': {
      id: '/chamada'
      path: '/chamada'
      fullPath: '/chamada'
      preLoaderRoute: typeof ChamadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aniversariantes': {
      id: '/aniversariantes'
      path: '/aniversariantes'
      fullPath: '/aniversariantes'
      preLoaderRoute: typeof AniversariantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-faltas': {
      id: '/analise-faltas'
      path: '/analise-faltas'
      fullPath: '/analise-faltas'
      preLoaderRoute: typeof AnaliseFaltasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaga/$token': {
      id: '/vaga/$token'
      path: '/vaga/$token'
      fullPath: '/vaga/$token'
      preLoaderRoute: typeof VagaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseFaltasRoute: AnaliseFaltasRoute,
  AniversariantesRoute: AniversariantesRoute,
  AuditoriaRoute: AuditoriaRoute,
  CadastroRoute: CadastroRoute,
  ChamadaRoute: ChamadaRoute,
  DashboardRoute: DashboardRoute,
  EmpresaConfigRoute: EmpresaConfigRoute,
  EmpresaMembrosRoute: EmpresaMembrosRoute,
  ExperienciaRoute: ExperienciaRoute,
  FeedbacksRoute: FeedbacksRoute,
  GeracoesRoute: GeracoesRoute,
  HistoricoAdmissoesRoute: HistoricoAdmissoesRoute,
  IdeiasRoute: IdeiasRoute,
  InicioRoute: InicioRoute,
  MapaAlocacaoRoute: MapaAlocacaoRoute,
  MestreRoute: MestreRoute,
  MovimentacoesAdmissoesRoute: MovimentacoesAdmissoesRoute,
  NotasRoute: NotasRoute,
  PesquisasRoute: PesquisasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SolicitacaoMovimentacaoRoute: SolicitacaoMovimentacaoRoute,
  UsuariosRoute: UsuariosRoute,
  ESlugRoute: ESlugRoute,
  PTokenRoute: PTokenRoute,
  VagaTokenRoute: VagaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
