/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as SolicitacaoMovimentacaoRouteImport } from './routes/solicitacao-movimentacao'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RedeSocialRouteImport } from './routes/rede-social'
import { Route as PesquisasRouteImport } from './routes/pesquisas'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as MovimentacoesAdmissoesRouteImport } from './routes/movimentacoes-admissoes'
import { Route as MestreRouteImport } from './routes/mestre'
import { Route as MapaAlocacaoRouteImport } from './routes/mapa-alocacao'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as IdeiasRouteImport } from './routes/ideias'
import { Route as HistoricoAdmissoesRouteImport } from './routes/historico-admissoes'
import { Route as GeracoesRouteImport } from './routes/geracoes'
import { Route as FeedbacksRouteImport } from './routes/feedbacks'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as EntrevistasDesligamentoRouteImport } from './routes/entrevistas-desligamento'
import { Route as EmpresaMembrosRouteImport } from './routes/empresa-membros'
import { Route as EmpresaConfigRouteImport } from './routes/empresa-config'
import { Route as DocumentosAdmissaoRouteImport } from './routes/documentos-admissao'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as ChamadaTerceirosRouteImport } from './routes/chamada-terceiros'
import { Route as ChamadaRouteImport } from './routes/chamada'
import { Route as CanalEticaRouteImport } from './routes/canal-etica'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BaseConhecimentoRouteImport } from './routes/base-conhecimento'
import { Route as BancoTalentosRouteImport } from './routes/banco-talentos'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AniversariantesRouteImport } from './routes/aniversariantes'
import { Route as AnaliseFaltasRouteImport } from './routes/analise-faltas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VagaTokenRouteImport } from './routes/vaga.$token'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as DocTokenRouteImport } from './routes/doc.$token'
import { Route as DesligamentoTokenRouteImport } from './routes/desligamento.$token'
import { Route as ESlugLoginRouteImport } from './routes/e.$slug.login'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitacaoMovimentacaoRoute = SolicitacaoMovimentacaoRouteImport.update({
  id: '/solicitacao-movimentacao',
  path: '/solicitacao-movimentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeSocialRoute = RedeSocialRouteImport.update({
  id: '/rede-social',
  path: '/rede-social',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisasRoute = PesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesAdmissoesRoute = MovimentacoesAdmissoesRouteImport.update({
  id: '/movimentacoes-admissoes',
  path: '/movimentacoes-admissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MestreRoute = MestreRouteImport.update({
  id: '/mestre',
  path: '/mestre',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaAlocacaoRoute = MapaAlocacaoRouteImport.update({
  id: '/mapa-alocacao',
  path: '/mapa-alocacao',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeiasRoute = IdeiasRouteImport.update({
  id: '/ideias',
  path: '/ideias',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoAdmissoesRoute = HistoricoAdmissoesRouteImport.update({
  id: '/historico-admissoes',
  path: '/historico-admissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GeracoesRoute = GeracoesRouteImport.update({
  id: '/geracoes',
  path: '/geracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbacksRoute = FeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrevistasDesligamentoRoute = EntrevistasDesligamentoRouteImport.update({
  id: '/entrevistas-desligamento',
  path: '/entrevistas-desligamento',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaMembrosRoute = EmpresaMembrosRouteImport.update({
  id: '/empresa-membros',
  path: '/empresa-membros',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaConfigRoute = EmpresaConfigRouteImport.update({
  id: '/empresa-config',
  path: '/empresa-config',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosAdmissaoRoute = DocumentosAdmissaoRouteImport.update({
  id: '/documentos-admissao',
  path: '/documentos-admissao',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadaTerceirosRoute = ChamadaTerceirosRouteImport.update({
  id: '/chamada-terceiros',
  path: '/chamada-terceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadaRoute = ChamadaRouteImport.update({
  id: '/chamada',
  path: '/chamada',
  getParentRoute: () => rootRouteImport,
} as any)
const CanalEticaRoute = CanalEticaRouteImport.update({
  id: '/canal-etica',
  path: '/canal-etica',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseConhecimentoRoute = BaseConhecimentoRouteImport.update({
  id: '/base-conhecimento',
  path: '/base-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const BancoTalentosRoute = BancoTalentosRouteImport.update({
  id: '/banco-talentos',
  path: '/banco-talentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AniversariantesRoute = AniversariantesRouteImport.update({
  id: '/aniversariantes',
  path: '/aniversariantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseFaltasRoute = AnaliseFaltasRouteImport.update({
  id: '/analise-faltas',
  path: '/analise-faltas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagaTokenRoute = VagaTokenRouteImport.update({
  id: '/vaga/$token',
  path: '/vaga/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocTokenRoute = DocTokenRouteImport.update({
  id: '/doc/$token',
  path: '/doc/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DesligamentoTokenRoute = DesligamentoTokenRouteImport.update({
  id: '/desligamento/$token',
  path: '/desligamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugLoginRoute = ESlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ESlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise-faltas': typeof AnaliseFaltasRoute
  '/aniversariantes': typeof AniversariantesRoute
  '/auditoria': typeof AuditoriaRoute
  '/avisos': typeof AvisosRoute
  '/banco-talentos': typeof BancoTalentosRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/cadastro': typeof CadastroRoute
  '/canal-etica': typeof CanalEticaRoute
  '/chamada': typeof ChamadaRoute
  '/chamada-terceiros': typeof ChamadaTerceirosRoute
  '/chamados': typeof ChamadosRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/documentos-admissao': typeof DocumentosAdmissaoRoute
  '/empresa-config': typeof EmpresaConfigRoute
  '/empresa-membros': typeof EmpresaMembrosRoute
  '/entrevistas-desligamento': typeof EntrevistasDesligamentoRoute
  '/experiencia': typeof ExperienciaRoute
  '/feedbacks': typeof FeedbacksRoute
  '/geracoes': typeof GeracoesRoute
  '/historico-admissoes': typeof HistoricoAdmissoesRoute
  '/ideias': typeof IdeiasRoute
  '/inicio': typeof InicioRoute
  '/mapa-alocacao': typeof MapaAlocacaoRoute
  '/mestre': typeof MestreRoute
  '/movimentacoes-admissoes': typeof MovimentacoesAdmissoesRoute
  '/notas': typeof NotasRoute
  '/pesquisas': typeof PesquisasRoute
  '/rede-social': typeof RedeSocialRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitacao-movimentacao': typeof SolicitacaoMovimentacaoRoute
  '/usuarios': typeof UsuariosRoute
  '/desligamento/$token': typeof DesligamentoTokenRoute
  '/doc/$token': typeof DocTokenRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/p/$token': typeof PTokenRoute
  '/vaga/$token': typeof VagaTokenRoute
  '/e/$slug/login': typeof ESlugLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise-faltas': typeof AnaliseFaltasRoute
  '/aniversariantes': typeof AniversariantesRoute
  '/auditoria': typeof AuditoriaRoute
  '/avisos': typeof AvisosRoute
  '/banco-talentos': typeof BancoTalentosRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/cadastro': typeof CadastroRoute
  '/canal-etica': typeof CanalEticaRoute
  '/chamada': typeof ChamadaRoute
  '/chamada-terceiros': typeof ChamadaTerceirosRoute
  '/chamados': typeof ChamadosRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/documentos-admissao': typeof DocumentosAdmissaoRoute
  '/empresa-config': typeof EmpresaConfigRoute
  '/empresa-membros': typeof EmpresaMembrosRoute
  '/entrevistas-desligamento': typeof EntrevistasDesligamentoRoute
  '/experiencia': typeof ExperienciaRoute
  '/feedbacks': typeof FeedbacksRoute
  '/geracoes': typeof GeracoesRoute
  '/historico-admissoes': typeof HistoricoAdmissoesRoute
  '/ideias': typeof IdeiasRoute
  '/inicio': typeof InicioRoute
  '/mapa-alocacao': typeof MapaAlocacaoRoute
  '/mestre': typeof MestreRoute
  '/movimentacoes-admissoes': typeof MovimentacoesAdmissoesRoute
  '/notas': typeof NotasRoute
  '/pesquisas': typeof PesquisasRoute
  '/rede-social': typeof RedeSocialRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitacao-movimentacao': typeof SolicitacaoMovimentacaoRoute
  '/usuarios': typeof UsuariosRoute
  '/desligamento/$token': typeof DesligamentoTokenRoute
  '/doc/$token': typeof DocTokenRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/p/$token': typeof PTokenRoute
  '/vaga/$token': typeof VagaTokenRoute
  '/e/$slug/login': typeof ESlugLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise-faltas': typeof AnaliseFaltasRoute
  '/aniversariantes': typeof AniversariantesRoute
  '/auditoria': typeof AuditoriaRoute
  '/avisos': typeof AvisosRoute
  '/banco-talentos': typeof BancoTalentosRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/cadastro': typeof CadastroRoute
  '/canal-etica': typeof CanalEticaRoute
  '/chamada': typeof ChamadaRoute
  '/chamada-terceiros': typeof ChamadaTerceirosRoute
  '/chamados': typeof ChamadosRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/documentos-admissao': typeof DocumentosAdmissaoRoute
  '/empresa-config': typeof EmpresaConfigRoute
  '/empresa-membros': typeof EmpresaMembrosRoute
  '/entrevistas-desligamento': typeof EntrevistasDesligamentoRoute
  '/experiencia': typeof ExperienciaRoute
  '/feedbacks': typeof FeedbacksRoute
  '/geracoes': typeof GeracoesRoute
  '/historico-admissoes': typeof HistoricoAdmissoesRoute
  '/ideias': typeof IdeiasRoute
  '/inicio': typeof InicioRoute
  '/mapa-alocacao': typeof MapaAlocacaoRoute
  '/mestre': typeof MestreRoute
  '/movimentacoes-admissoes': typeof MovimentacoesAdmissoesRoute
  '/notas': typeof NotasRoute
  '/pesquisas': typeof PesquisasRoute
  '/rede-social': typeof RedeSocialRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitacao-movimentacao': typeof SolicitacaoMovimentacaoRoute
  '/usuarios': typeof UsuariosRoute
  '/desligamento/$token': typeof DesligamentoTokenRoute
  '/doc/$token': typeof DocTokenRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/p/$token': typeof PTokenRoute
  '/vaga/$token': typeof VagaTokenRoute
  '/e/$slug/login': typeof ESlugLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise-faltas'
    | '/aniversariantes'
    | '/auditoria'
    | '/avisos'
    | '/banco-talentos'
    | '/base-conhecimento'
    | '/cadastro'
    | '/canal-etica'
    | '/chamada'
    | '/chamada-terceiros'
    | '/chamados'
    | '/crm'
    | '/dashboard'
    | '/documentos-admissao'
    | '/empresa-config'
    | '/empresa-membros'
    | '/entrevistas-desligamento'
    | '/experiencia'
    | '/feedbacks'
    | '/geracoes'
    | '/historico-admissoes'
    | '/ideias'
    | '/inicio'
    | '/mapa-alocacao'
    | '/mestre'
    | '/movimentacoes-admissoes'
    | '/notas'
    | '/pesquisas'
    | '/rede-social'
    | '/reset-password'
    | '/solicitacao-movimentacao'
    | '/usuarios'
    | '/desligamento/$token'
    | '/doc/$token'
    | '/e/$slug'
    | '/p/$token'
    | '/vaga/$token'
    | '/e/$slug/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise-faltas'
    | '/aniversariantes'
    | '/auditoria'
    | '/avisos'
    | '/banco-talentos'
    | '/base-conhecimento'
    | '/cadastro'
    | '/canal-etica'
    | '/chamada'
    | '/chamada-terceiros'
    | '/chamados'
    | '/crm'
    | '/dashboard'
    | '/documentos-admissao'
    | '/empresa-config'
    | '/empresa-membros'
    | '/entrevistas-desligamento'
    | '/experiencia'
    | '/feedbacks'
    | '/geracoes'
    | '/historico-admissoes'
    | '/ideias'
    | '/inicio'
    | '/mapa-alocacao'
    | '/mestre'
    | '/movimentacoes-admissoes'
    | '/notas'
    | '/pesquisas'
    | '/rede-social'
    | '/reset-password'
    | '/solicitacao-movimentacao'
    | '/usuarios'
    | '/desligamento/$token'
    | '/doc/$token'
    | '/e/$slug'
    | '/p/$token'
    | '/vaga/$token'
    | '/e/$slug/login'
  id:
    | '__root__'
    | '/'
    | '/analise-faltas'
    | '/aniversariantes'
    | '/auditoria'
    | '/avisos'
    | '/banco-talentos'
    | '/base-conhecimento'
    | '/cadastro'
    | '/canal-etica'
    | '/chamada'
    | '/chamada-terceiros'
    | '/chamados'
    | '/crm'
    | '/dashboard'
    | '/documentos-admissao'
    | '/empresa-config'
    | '/empresa-membros'
    | '/entrevistas-desligamento'
    | '/experiencia'
    | '/feedbacks'
    | '/geracoes'
    | '/historico-admissoes'
    | '/ideias'
    | '/inicio'
    | '/mapa-alocacao'
    | '/mestre'
    | '/movimentacoes-admissoes'
    | '/notas'
    | '/pesquisas'
    | '/rede-social'
    | '/reset-password'
    | '/solicitacao-movimentacao'
    | '/usuarios'
    | '/desligamento/$token'
    | '/doc/$token'
    | '/e/$slug'
    | '/p/$token'
    | '/vaga/$token'
    | '/e/$slug/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseFaltasRoute: typeof AnaliseFaltasRoute
  AniversariantesRoute: typeof AniversariantesRoute
  AuditoriaRoute: typeof AuditoriaRoute
  AvisosRoute: typeof AvisosRoute
  BancoTalentosRoute: typeof BancoTalentosRoute
  BaseConhecimentoRoute: typeof BaseConhecimentoRoute
  CadastroRoute: typeof CadastroRoute
  CanalEticaRoute: typeof CanalEticaRoute
  ChamadaRoute: typeof ChamadaRoute
  ChamadaTerceirosRoute: typeof ChamadaTerceirosRoute
  ChamadosRoute: typeof ChamadosRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  DocumentosAdmissaoRoute: typeof DocumentosAdmissaoRoute
  EmpresaConfigRoute: typeof EmpresaConfigRoute
  EmpresaMembrosRoute: typeof EmpresaMembrosRoute
  EntrevistasDesligamentoRoute: typeof EntrevistasDesligamentoRoute
  ExperienciaRoute: typeof ExperienciaRoute
  FeedbacksRoute: typeof FeedbacksRoute
  GeracoesRoute: typeof GeracoesRoute
  HistoricoAdmissoesRoute: typeof HistoricoAdmissoesRoute
  IdeiasRoute: typeof IdeiasRoute
  InicioRoute: typeof InicioRoute
  MapaAlocacaoRoute: typeof MapaAlocacaoRoute
  MestreRoute: typeof MestreRoute
  MovimentacoesAdmissoesRoute: typeof MovimentacoesAdmissoesRoute
  NotasRoute: typeof NotasRoute
  PesquisasRoute: typeof PesquisasRoute
  RedeSocialRoute: typeof RedeSocialRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SolicitacaoMovimentacaoRoute: typeof SolicitacaoMovimentacaoRoute
  UsuariosRoute: typeof UsuariosRoute
  DesligamentoTokenRoute: typeof DesligamentoTokenRoute
  DocTokenRoute: typeof DocTokenRoute
  ESlugRoute: typeof ESlugRouteWithChildren
  PTokenRoute: typeof PTokenRoute
  VagaTokenRoute: typeof VagaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitacao-movimentacao': {
      id: '/solicitacao-movimentacao'
      path: '/solicitacao-movimentacao'
      fullPath: '/solicitacao-movimentacao'
      preLoaderRoute: typeof SolicitacaoMovimentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rede-social': {
      id: '/rede-social'
      path: '/rede-social'
      fullPath: '/rede-social'
      preLoaderRoute: typeof RedeSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisas': {
      id: '/pesquisas'
      path: '/pesquisas'
      fullPath: '/pesquisas'
      preLoaderRoute: typeof PesquisasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes-admissoes': {
      id: '/movimentacoes-admissoes'
      path: '/movimentacoes-admissoes'
      fullPath: '/movimentacoes-admissoes'
      preLoaderRoute: typeof MovimentacoesAdmissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mestre': {
      id: '/mestre'
      path: '/mestre'
      fullPath: '/mestre'
      preLoaderRoute: typeof MestreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-alocacao': {
      id: '/mapa-alocacao'
      path: '/mapa-alocacao'
      fullPath: '/mapa-alocacao'
      preLoaderRoute: typeof MapaAlocacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideias': {
      id: '/ideias'
      path: '/ideias'
      fullPath: '/ideias'
      preLoaderRoute: typeof IdeiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico-admissoes': {
      id: '/historico-admissoes'
      path: '/historico-admissoes'
      fullPath: '/historico-admissoes'
      preLoaderRoute: typeof HistoricoAdmissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geracoes': {
      id: '/geracoes'
      path: '/geracoes'
      fullPath: '/geracoes'
      preLoaderRoute: typeof GeracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedbacks': {
      id: '/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof FeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrevistas-desligamento': {
      id: '/entrevistas-desligamento'
      path: '/entrevistas-desligamento'
      fullPath: '/entrevistas-desligamento'
      preLoaderRoute: typeof EntrevistasDesligamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa-membros': {
      id: '/empresa-membros'
      path: '/empresa-membros'
      fullPath: '/empresa-membros'
      preLoaderRoute: typeof EmpresaMembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa-config': {
      id: '/empresa-config'
      path: '/empresa-config'
      fullPath: '/empresa-config'
      preLoaderRoute: typeof EmpresaConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos-admissao': {
      id: '/documentos-admissao'
      path: '/documentos-admissao'
      fullPath: '/documentos-admissao'
      preLoaderRoute: typeof DocumentosAdmissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamada-terceiros': {
      id: '/chamada-terceiros'
      path: '/chamada-terceiros'
      fullPath: '/chamada-terceiros'
      preLoaderRoute: typeof ChamadaTerceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamada': {
      id: '/chamada'
      path: '/chamada'
      fullPath: '/chamada'
      preLoaderRoute: typeof ChamadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canal-etica': {
      id: '/canal-etica'
      path: '/canal-etica'
      fullPath: '/canal-etica'
      preLoaderRoute: typeof CanalEticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-conhecimento': {
      id: '/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento'
      preLoaderRoute: typeof BaseConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banco-talentos': {
      id: '/banco-talentos'
      path: '/banco-talentos'
      fullPath: '/banco-talentos'
      preLoaderRoute: typeof BancoTalentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aniversariantes': {
      id: '/aniversariantes'
      path: '/aniversariantes'
      fullPath: '/aniversariantes'
      preLoaderRoute: typeof AniversariantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-faltas': {
      id: '/analise-faltas'
      path: '/analise-faltas'
      fullPath: '/analise-faltas'
      preLoaderRoute: typeof AnaliseFaltasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaga/$token': {
      id: '/vaga/$token'
      path: '/vaga/$token'
      fullPath: '/vaga/$token'
      preLoaderRoute: typeof VagaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$token': {
      id: '/doc/$token'
      path: '/doc/$token'
      fullPath: '/doc/$token'
      preLoaderRoute: typeof DocTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desligamento/$token': {
      id: '/desligamento/$token'
      path: '/desligamento/$token'
      fullPath: '/desligamento/$token'
      preLoaderRoute: typeof DesligamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug/login': {
      id: '/e/$slug/login'
      path: '/login'
      fullPath: '/e/$slug/login'
      preLoaderRoute: typeof ESlugLoginRouteImport
      parentRoute: typeof ESlugRoute
    }
  }
}

interface ESlugRouteChildren {
  ESlugLoginRoute: typeof ESlugLoginRoute
}

const ESlugRouteChildren: ESlugRouteChildren = {
  ESlugLoginRoute: ESlugLoginRoute,
}

const ESlugRouteWithChildren = ESlugRoute._addFileChildren(ESlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseFaltasRoute: AnaliseFaltasRoute,
  AniversariantesRoute: AniversariantesRoute,
  AuditoriaRoute: AuditoriaRoute,
  AvisosRoute: AvisosRoute,
  BancoTalentosRoute: BancoTalentosRoute,
  BaseConhecimentoRoute: BaseConhecimentoRoute,
  CadastroRoute: CadastroRoute,
  CanalEticaRoute: CanalEticaRoute,
  ChamadaRoute: ChamadaRoute,
  ChamadaTerceirosRoute: ChamadaTerceirosRoute,
  ChamadosRoute: ChamadosRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  DocumentosAdmissaoRoute: DocumentosAdmissaoRoute,
  EmpresaConfigRoute: EmpresaConfigRoute,
  EmpresaMembrosRoute: EmpresaMembrosRoute,
  EntrevistasDesligamentoRoute: EntrevistasDesligamentoRoute,
  ExperienciaRoute: ExperienciaRoute,
  FeedbacksRoute: FeedbacksRoute,
  GeracoesRoute: GeracoesRoute,
  HistoricoAdmissoesRoute: HistoricoAdmissoesRoute,
  IdeiasRoute: IdeiasRoute,
  InicioRoute: InicioRoute,
  MapaAlocacaoRoute: MapaAlocacaoRoute,
  MestreRoute: MestreRoute,
  MovimentacoesAdmissoesRoute: MovimentacoesAdmissoesRoute,
  NotasRoute: NotasRoute,
  PesquisasRoute: PesquisasRoute,
  RedeSocialRoute: RedeSocialRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SolicitacaoMovimentacaoRoute: SolicitacaoMovimentacaoRoute,
  UsuariosRoute: UsuariosRoute,
  DesligamentoTokenRoute: DesligamentoTokenRoute,
  DocTokenRoute: DocTokenRoute,
  ESlugRoute: ESlugRouteWithChildren,
  PTokenRoute: PTokenRoute,
  VagaTokenRoute: VagaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
